[package]
name = "friend_fi"
version = "1.0.0"
authors = []

[addresses]
friend_fi = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
