[package]
name = "friend_fi"
version = "1.0.0"
authors = []

[addresses]
friend_fi = "0x9eca6c1a4ff54edb2b6bacfbaa8b070a44d288fff5334942410aad332cc1f7bf"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
