[package]
name = "friend_fi"
version = "1.0.0"
authors = []

[addresses]
friend_fi = "0x92fc2d6ee1330193f039a0f87b221743ec77ac08e640a1470d4f45c566783448"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
